"""Hypothesis data models."""
from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class HypothesisStatus(str, Enum):
    """Hypothesis generation status."""

    PENDING = "PENDING"
    GENERATING = "GENERATING"
    VALIDATING = "VALIDATING"
    DEBATING = "DEBATING"
    RANKING = "RANKING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class HypothesisScore(BaseModel):
    """Hypothesis evaluation scores."""

    novelty: float = Field(..., ge=0.0, le=100.0, description="Novelty score (0-100)")
    feasibility: float = Field(..., ge=0.0, le=100.0, description="Feasibility score (0-100)")
    impact: float = Field(..., ge=0.0, le=100.0, description="Impact score (0-100)")
    overall: float = Field(..., ge=0.0, le=100.0, description="Overall score (0-100)")
    
    validator_score: Optional[float] = Field(
        None, ge=0.0, le=100.0, description="Validator agent score"
    )
    ranker_score: Optional[float] = Field(
        None, ge=0.0, le=100.0, description="Ranker agent score"
    )
    
    confidence: float = Field(
        default=1.0, ge=0.0, le=1.0, description="Score confidence"
    )


class HypothesisEvidence(BaseModel):
    """Evidence supporting a hypothesis."""

    paper_id: str = Field(..., description="arXiv ID of supporting paper")
    quote: str = Field(..., description="Relevant quote from paper")
    relevance_score: float = Field(..., ge=0.0, le=1.0, description="Relevance score")
    page: Optional[int] = Field(None, description="Page number in paper")


class Hypothesis(BaseModel):
    """Scientific hypothesis generated by agents."""

    id: str = Field(..., description="Unique hypothesis ID")
    text: str = Field(..., description="Hypothesis statement")
    description: str = Field(..., description="Detailed description")
    
    # Scores
    score: HypothesisScore = Field(..., description="Evaluation scores")
    
    # Supporting evidence
    evidence: List[HypothesisEvidence] = Field(
        default_factory=list, description="Supporting evidence from papers"
    )
    source_papers: List[str] = Field(
        default_factory=list, description="Source paper arXiv IDs"
    )
    
    # Agent metadata
    generated_by: str = Field(default="generator", description="Agent that generated this")
    validated_by: Optional[str] = Field(None, description="Agent that validated this")
    feedback: List[str] = Field(default_factory=list, description="Validation feedback")
    
    # Clustering
    cluster_id: Optional[int] = Field(None, description="Cluster ID (if clustered)")
    
    # Status
    status: HypothesisStatus = Field(
        default=HypothesisStatus.PENDING, description="Generation status"
    )
    
    # Timestamps
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        """Pydantic config."""

        json_schema_extra = {
            "example": {
                "id": "hyp_abc123",
                "text": "Quantum entanglement can be used to improve error correction in topological qubits",
                "description": "By leveraging quantum entanglement properties, we can develop more robust error correction schemes...",
                "score": {
                    "novelty": 85.0,
                    "feasibility": 75.0,
                    "impact": 90.0,
                    "overall": 83.3,
                },
                "source_papers": ["2301.12345", "2302.67890"],
                "status": "COMPLETED",
            }
        }


class HypothesisCluster(BaseModel):
    """Cluster of similar hypotheses."""

    cluster_id: int = Field(..., description="Cluster ID")
    hypotheses: List[str] = Field(..., description="Hypothesis IDs in this cluster")
    centroid_text: str = Field(..., description="Representative text for this cluster")
    diversity_score: float = Field(
        ..., ge=0.0, le=1.0, description="Diversity score within cluster"
    )
    size: int = Field(..., gt=0, description="Number of hypotheses in cluster")
    
    # Top hypothesis in cluster
    best_hypothesis_id: Optional[str] = Field(
        None, description="ID of highest-scoring hypothesis"
    )
    average_score: float = Field(..., ge=0.0, le=100.0, description="Average overall score")


class HypothesisGenerationRequest(BaseModel):
    """Request to generate hypotheses."""

    paper_ids: List[str] = Field(
        ..., min_length=1, max_length=20, description="arXiv IDs to generate hypotheses from"
    )
    max_hypotheses: int = Field(
        default=5, gt=0, le=10, description="Maximum hypotheses to generate"
    )
    debate_rounds: int = Field(
        default=3, gt=0, le=5, description="Number of debate rounds"
    )
    clustering: bool = Field(
        default=True, description="Whether to cluster results"
    )


class HypothesisGenerationResponse(BaseModel):
    """Response with generated hypotheses."""

    request_id: str = Field(..., description="Unique request ID")
    hypotheses: List[Hypothesis] = Field(..., description="Generated hypotheses")
    clusters: List[HypothesisCluster] = Field(
        default_factory=list, description="Hypothesis clusters"
    )
    
    # Metadata
    total_papers: int = Field(..., description="Number of papers processed")
    generation_time_seconds: float = Field(..., description="Time taken to generate")
    
    status: HypothesisStatus = Field(..., description="Overall status")
